# This pipeline will:
# - Check if container already exists, if not it will create it.
# - Rehydrate archived snapshot files, from Archived to Hot.
# 
#
# The variables is provided by Variable group with the name: variable_iScaleArchive
#
#
# Pipeline are used with User assigned managed identity
#
# This pipeline also expects an Azure (Resource Manager) service connection in Azure DevOps with the name 'connection_snapshottestsa', using Workload Identity federation (manual). This service connection must have been set up in the Project Settings.


trigger: none
pr: none

pool:
  name: easec-pool
  
variables:
  storage-account: snapshottestsa
  subscriptionId: "0ac447d7-fbc3-4d3d-84d4-37bb9a71e089"
  source-container: "iscala-archive"
  source-blob-os: "easec-vm_OsDisk_1_snap.vhd"
  source-blob-data: "easec-vm_DataDisk_1_snap.vhd"
  dest-container: "snapshot"
  dest-blob-os: "easec-vm_OsDisk_1_snap.vhd"
  dest-blob-data: "easec-vm_DataDisk_1_snap.vhd"

stages:
- stage: check_container_exist
  jobs:
  - job:
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'connection_snapshottestsa'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            exist=$(az storage container exists --account-name "$(storage-account)" --auth-mode login --name "$(dest-container)" --query [exists] -o tsv)
            echo $exist
            if [ "$exist" = "true" ]; then
              echo "Container exist"
            else
              echo "Container does´nt exist"
              az storage container create --name "$(dest-container)" --account-name "$(storage-account)" --auth-mode login
            fi
          
- stage: re_hydrate
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: 'connection_snapshottestsa'
         scriptType: pscore
         scriptLocation: inlineScript
         inlineScript: |
          az storage blob copy start --source-container "$(source-container)" --source-blob "$(source-blob-os)" --destination-container "$(dest-container)" --destination-blob "$(dest-blob-os)" --account-name "$(storage-account)" --auth-mode login --tier hot --rehydrate-priority standard
          az storage blob copy start --source-container "$(source-container)" --source-blob "$(source-blob-data)" --destination-container "$(dest-container)" --destination-blob "$(dest-blob-data)" --account-name "$(storage-account)" --auth-mode login --tier hot --rehydrate-priority standard
