# This pipeline will:
# - Check if container already exists, if not it will create it.
# - Rehydrate archived snapshot files, from Archived to Hot.
# - Enable and start Logic App.
# 
#
# The variables are provided by Variable group with the name: variable_iScaleArchive
#
#
# Pipeline are used with User assigned managed identity
#
# This pipeline also expects Azure (Resource Manager) service connections in Azure DevOps with the name 'connection_snapshottestsa' and 'connection_subscription' , using Workload Identity federation (manual). This service connections must have been set up in the Project Settings.


trigger: none
pr: none

pool:
  name: easec-pool
  
variables:
- group: variable_iScaleArchive

stages:
- stage: check_container_exist
  jobs:
  - job:
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: "connection_snapshottestsa"
          scriptType: "bash"
          scriptLocation: "inlineScript"
          inlineScript: |
            exist=$(az storage container exists --account-name "$(storageAccount)" --auth-mode login --name "$(containerName)" --query [exists] -o tsv)
            echo $exist
            if [ "$exist" = "true" ]; then
              echo "Container exist"
            else
              echo "Container does´nt exist"
              az storage container create --name "$(containerName)" --account-name "$(storageAccount)" --auth-mode login
            fi

- stage: start_logic_app
  jobs:
  - job:
    steps:
    - task: AzurePowerShell@5
      inputs:
       azureSubscription: "connection_subscription"
       azurePowerShellVersion: "LatestVersion"
       scriptType: "InlineScript"
       Inline: |
        Set-AzLogicApp -ResourceGroupName "$(resourceGroupResources)" -Name "$(logicAppName)" -State "Enabled" -Force
        Start-AzLogicApp -ResourceGroupName "$(resourceGroupResources)" -Name "$(logicAppName)" -TriggerName "$(triggerName)"
        
- stage: re_hydrate
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: "connection_snapshottestsa"
         scriptType: "pscore"
         scriptLocation: "inlineScript"
         inlineScript: |
          az storage blob copy start --source-container "$(sourceContainer)" --source-blob "$(sourceBlobOs)" --destination-container "$(containerName)" --destination-blob "$(destinationBlobOs)" --account-name "$(storageAccount)" --auth-mode login --tier hot --rehydrate-priority standard
          az storage blob copy start --source-container "$(sourceContainer)" --source-blob "$(sourceBlobData)" --destination-container "$(containerName)" --destination-blob "$(destinationBlobData)" --account-name "$(storageAccount)" --auth-mode login --tier hot --rehydrate-priority standard