trigger: none
pr: none

parameters:
- name: targetEnv
  type: string
  default: dev
  values:
  - dev
  - prod

- name: azureServiceConnection
  type: string
  default: Azure-Service-Connection-Sub

variables:
- name: sharedStorageAccountName
  value: snapshottestsa

- name: sharedContainerName
  value: snapshot

# DEV
- ${{ if eq(parameters.targetEnv, 'dev') }}:
  - group: variable_iScalaArchive
  - name: resourceGroupName
    value: rg-iscala-archive-dev
  - name: rgLocation
    value: swedencentral
  - name: keyVaultName
    value: kv-iscala-archive-dev
  - name: deploymentEnvironment
    value: ''

# PROD
- ${{ if eq(parameters.targetEnv, 'prod') }}:
  - group: variable_iScalaArchive-prod
  - name: resourceGroupName
    value: rg-iscala-archive-prod
  - name: rgLocation
    value: swedencentral
  - name: keyVaultName
    value: kv-iscala-archive-prod
  - name: deploymentEnvironment
    value: iscala-archive-prod

stages:
- stage: Remove
  displayName: Remove ${{ parameters.targetEnv }}
  jobs:

  - ${{ if eq(parameters.targetEnv, 'dev') }}:
    - job: RemoveDev
      displayName: Remove DEV
      pool:
        name: easec-pool
      steps:
      - template: templates/remove_env_steps.yml
        parameters:
          azureServiceConnection: ${{ parameters.azureServiceConnection }}
          resourceGroupName: $(resourceGroupName)
          rgLocation: $(rgLocation)
          keyVaultName: $(keyVaultName)
          storageAccountName: $(sharedStorageAccountName)
          sharedContainerName: $(sharedContainerName)

  - ${{ if eq(parameters.targetEnv, 'prod') }}:
    - deployment: RemoveProd
      displayName: Remove PROD (requires approval)
      environment: $(deploymentEnvironment)
      pool:
        name: easec-pool
      strategy:
        runOnce:
          deploy:
            steps:
            - template: templates/remove_env_steps.yml
              parameters:
                azureServiceConnection: ${{ parameters.azureServiceConnection }}
                resourceGroupName: $(resourceGroupName)
                rgLocation: $(rgLocation)
                keyVaultName: $(keyVaultName)
                storageAccountName: $(sharedStorageAccountName)
                sharedContainerName: $(sharedContainerName)
